### ISSUE TITLE
Cannot download offers

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware/qoffer-portlet#3]
Steps to replicate:

1. Click on the _Offer manager_ tab.
2. Select the first project (could replicate with the first two project).
3. Click on the _Download offer_ button.
4. Following exception appears on the server log:

```
org.docx4j.openpackaging.exceptions.Docx4JException: Error processing zip file (is it a zip file?)
        at org.docx4j.openpackaging.io3.stores.ZipPartStore.<init>(ZipPartStore.java:123)
        at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:460)
        at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:379)
        at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:270)
        at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:250)
        at org.docx4j.openpackaging.packages.WordprocessingMLPackage.load(WordprocessingMLPackage.java:168)
        at life.qbic.utils.Docx4jUtils.applyBindings(Docx4jUtils.java:44)
        at life.qbic.components.OfferManagerTab.generateOfferFile(OfferManagerTab.java:569)
        at life.qbic.components.OfferManagerTab.access$300(OfferManagerTab.java:45)
        at life.qbic.components.OfferManagerTab$3.handleConnectorRequest(OfferManagerTab.java:404)

```

**Comment by chahuistle** [comment]
This is related to https://github.com/qbicsoftware/parent-poms/issues/27

**Comment by chahuistle** [comment]
Fixed in https://github.com/qbicsoftware/qoffer-portlet/pull/4
